// Generated by fetch-ivs-config.ts
export const ivsConfig = {
  "channelArn": "arn:aws:ivs:us-east-1:525894077320:channel/TcsBvlzhRKpH",
  "chatRoomArn": "arn:aws:ivschat:us-east-1:525894077320:room/PHGdv2iCGEY4",
  "playbackUrl": "https://a6682476db5e.us-east-1.playback.live-video.net/api/video/v1/us-east-1.525894077320.channel.TcsBvlzhRKpH.m3u8",
  "ingestEndpoint": "a6682476db5e.global-contribute.live-video.net",
  "webSocketEndpoint": "wss://edge.ivschat.us-east-1.amazonaws.com"
} as const;
